<<<<<<< HEAD
=======
import Head from 'next/head'
import { Inter } from '@next/font/google'
>>>>>>> feature/aziz/login_page

export default function Overview() {
  return (
<<<<<<< HEAD
    <div className='flex h-full flex-col justify-center items-center '>
      <h3 className='text-4xl mb-5 font-bold'>Overview</h3>
    </div>

  );
=======
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
>>>>>>> feature/aziz/login_page
}
